import {
  Beef,
  Salad,
  Pizza,
  Cake,
  Leaf,
  Coffee,
  Sun,
  Moon,
  Cookie,
  Wine,
  TrendingDown,
  Dumbbell,
  Fish,
  Wheat,
  Milk,
  Soup,
  Utensils,
  DollarSign,
  Apple,
  Heart,
} from "lucide-react-native";

// Colors
export const COLORS = {
  primary: "#70AD47",
  background: "#ffffff",
  cardBg: "#ffffff",
  textPrimary: "#111827",
  textSecondary: "#6b7280",
  textTertiary: "#9ca3af",

  // Category colors
  meat: "#f97316",
  vegetarian: "#16a34a",
  quickMeals: "#ef4444",
  desserts: "#f97316",
  vegan: "#84cc16",
  breakfast: "#f59e0b",
  lunch: "#3b82f6",
  dinner: "#8b5cf6",
  snacks: "#ec4899",
  drinks: "#06b6d4",
  lowCal: "#10b981",
  highProtein: "#dc2626",
  pescetarian: "#0ea5e9",
  seafood: "#06b6d4",
  glutenFree: "#f59e0b",
  dairyFree: "#a855f7",
  soup: "#fb923c",
  appetizers: "#ec4899",
  budget: "#22c55e",
  healthy: "#84cc16",
  comfort: "#f43f5e",

  // Border colors (20% opacity)
  borderMeat: "rgba(249, 115, 22, 0.2)",
  borderVegetarian: "rgba(22, 163, 74, 0.2)",
  borderQuickMeals: "rgba(239, 68, 68, 0.2)",
  borderDesserts: "rgba(249, 115, 22, 0.2)",
  borderVegan: "rgba(132, 204, 22, 0.2)",
  borderBreakfast: "rgba(245, 158, 11, 0.2)",
  borderLunch: "rgba(59, 130, 246, 0.2)",
  borderDinner: "rgba(139, 92, 246, 0.2)",
  borderSnacks: "rgba(236, 72, 153, 0.2)",
  borderDrinks: "rgba(6, 182, 212, 0.2)",
  borderLowCal: "rgba(16, 185, 129, 0.2)",
  borderHighProtein: "rgba(220, 38, 38, 0.2)",
  borderPescetarian: "rgba(14, 165, 233, 0.2)",
  borderSeafood: "rgba(6, 182, 212, 0.2)",
  borderGlutenFree: "rgba(245, 158, 11, 0.2)",
  borderDairyFree: "rgba(168, 85, 247, 0.2)",
  borderSoup: "rgba(251, 146, 60, 0.2)",
  borderAppetizers: "rgba(236, 72, 153, 0.2)",
  borderBudget: "rgba(34, 197, 94, 0.2)",
  borderHealthy: "rgba(132, 204, 22, 0.2)",
  borderComfort: "rgba(244, 63, 94, 0.2)",
};

// Typography
export const TYPOGRAPHY = {
  header: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: "#111827",
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "400" as const,
    color: "#6b7280",
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: "500" as const,
    color: "#1f2937",
  },
};

// Spacing & Dimensions
export const SPACING = {
  containerPadding: 20,
  headerMarginBottom: 24,
  gridGap: 16,
  cardPadding: 12,
  iconSize: 32,
  cardSize: 100,
  borderRadius: 16,
  iconBorderRadius: 14,
};

// Shadows
export const SHADOWS = {
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardPressed: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  backButton: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
};

// Category data
export const CATEGORIES = [
  {
    id: "meat",
    icon: Beef,
    label: "Meat",
    color: COLORS.meat,
    borderColor: COLORS.borderMeat,
    query: "meat",
  },
  {
    id: "vegetarian",
    icon: Salad,
    label: "Vegetarian",
    color: COLORS.vegetarian,
    borderColor: COLORS.borderVegetarian,
    query: "vegetarian",
  },
  {
    id: "quick-meals",
    icon: Pizza,
    label: "Quick Meals",
    color: COLORS.quickMeals,
    borderColor: COLORS.borderQuickMeals,
    query: "quick,easy",
  },
  {
    id: "desserts",
    icon: Cake,
    label: "Desserts",
    color: COLORS.desserts,
    borderColor: COLORS.borderDesserts,
    query: "dessert",
  },
  {
    id: "vegan",
    icon: Leaf,
    label: "Vegan",
    color: COLORS.vegan,
    borderColor: COLORS.borderVegan,
    query: "vegan",
  },
  {
    id: "breakfast",
    icon: Coffee,
    label: "Breakfast",
    color: COLORS.breakfast,
    borderColor: COLORS.borderBreakfast,
    query: "breakfast",
  },
  {
    id: "lunch",
    icon: Sun,
    label: "Lunch",
    color: COLORS.lunch,
    borderColor: COLORS.borderLunch,
    query: "lunch",
  },
  {
    id: "dinner",
    icon: Moon,
    label: "Dinner",
    color: COLORS.dinner,
    borderColor: COLORS.borderDinner,
    query: "dinner",
  },
  {
    id: "snacks",
    icon: Cookie,
    label: "Snacks",
    color: COLORS.snacks,
    borderColor: COLORS.borderSnacks,
    query: "snack",
  },
  {
    id: "drinks",
    icon: Wine,
    label: "Drinks",
    color: COLORS.drinks,
    borderColor: COLORS.borderDrinks,
    query: "drink,beverage",
  },
  {
    id: "low-calorie",
    icon: TrendingDown,
    label: "Low-Calorie",
    color: COLORS.lowCal,
    borderColor: COLORS.borderLowCal,
    query: "low calorie",
  },
  {
    id: "high-protein",
    icon: Dumbbell,
    label: "High-Protein",
    color: COLORS.highProtein,
    borderColor: COLORS.borderHighProtein,
    query: "high protein",
  },
  {
    id: "pescetarian",
    icon: Fish,
    label: "Pescetarian",
    color: COLORS.pescetarian,
    borderColor: COLORS.borderPescetarian,
    query: "pescetarian",
  },
  {
    id: "seafood",
    icon: Fish,
    label: "Seafood",
    color: COLORS.seafood,
    borderColor: COLORS.borderSeafood,
    query: "seafood,fish,shrimp",
  },
  {
    id: "gluten-free",
    icon: Wheat,
    label: "Gluten-Free",
    color: COLORS.glutenFree,
    borderColor: COLORS.borderGlutenFree,
    query: "gluten free",
  },
  {
    id: "dairy-free",
    icon: Milk,
    label: "Dairy-Free",
    color: COLORS.dairyFree,
    borderColor: COLORS.borderDairyFree,
    query: "dairy free",
  },
  {
    id: "soup",
    icon: Soup,
    label: "Soups",
    color: COLORS.soup,
    borderColor: COLORS.borderSoup,
    query: "soup",
  },
  {
    id: "appetizers",
    icon: Utensils,
    label: "Appetizers",
    color: COLORS.appetizers,
    borderColor: COLORS.borderAppetizers,
    query: "appetizer,starter",
  },
  {
    id: "budget",
    icon: DollarSign,
    label: "Budget-Friendly",
    color: COLORS.budget,
    borderColor: COLORS.borderBudget,
    query: "cheap,budget,inexpensive",
  },
  {
    id: "healthy",
    icon: Apple,
    label: "Healthy",
    color: COLORS.healthy,
    borderColor: COLORS.borderHealthy,
    query: "healthy,nutritious",
  },
  {
    id: "comfort",
    icon: Heart,
    label: "Comfort Food",
    color: COLORS.comfort,
    borderColor: COLORS.borderComfort,
    query: "comfort food",
  },
];
